# Render Blueprint: Deploys backend (Express) and frontend (Vite) from this repo

services:
  - name: flatmate-finder-backend
    type: web
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRE
        value: 7d
      - key: MONGODB_URI
        sync: false # set in Render Dashboard (use your Atlas URI with DB name)
      - key: JWT_SECRET
        sync: false # set in Render Dashboard
      - key: FRONTEND_URL
        sync: false # set to your frontend Render URL after first deploy

  - name: flatmate-finder-frontend
    type: static
    env: static
    plan: free
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        # Set this to your backend URL + /api, for example:
        # https://flatmate-finder-backend.onrender.com/api
        sync: false
    routes:
      # SPA routing: send all non-file requests to index.html
      - type: rewrite
        source: /*
        destination: /index.html
